version: '3'
services:
  postgres:
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: password
    image: postgres
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    expose:
      - "5432"

